"""List, per story node, the measures the ledger lost.

The portfolio is restated by the actor each turn rather than held by the
framework, so measures go missing (see
`docs/proposals/persistent-state-custody.md`). This maps each occurrence onto
the story node a writer would be working in, because prose written from a run
should not describe a measure the portfolio never carried.

Two kinds:

* **never entered** — proposed in this turn, never present in the portfolio at
  any later turn of the run. The turn that proposes it may narrate the
  proposal; nothing afterwards should treat it as running.
* **vanished** — present in this turn's portfolio and absent from the next,
  without having finished and without a cancellation line.

Writes `ledger-gaps.md`. Regenerate after any change to the path runs.

Usage:
    python scenarios/europe-2032/story/ledger_gaps.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

STORY = Path(__file__).resolve().parent
SCENARIO = STORY.parent
REPO = SCENARIO.parents[1]
sys.path.insert(0, str(REPO / "scripts"))
from build_dashboard import parse_actor_turn  # noqa: E402
from check_ledger import DEFERRED, same, words  # noqa: E402


def main() -> int:
    tree = json.loads((STORY / "tree.json").read_text(encoding="utf-8"))
    periods = tree["turn_periods"]
    # Read the front matter, do not grep: the scaffold's own instruction line
    # is "then set status: written", which a substring test matches.
    written = set()
    for path in STORY.glob("tree/*/narrative.md"):
        head = re.match(r"^---\n(.*?)\n---\n", path.read_text(encoding="utf-8"), re.S)
        if head and re.search(r"^status:\s*written\s*$", head.group(1), re.M):
            written.add(path.parent.name)

    rows: list[dict] = []
    for block in tree["blocks"]:
        rd = SCENARIO / "runs" / block["run"]
        turns = sorted(int(d.name.split("-")[1]) for d in rd.glob("turn-*"))
        parsed = {t: parse_actor_turn(rd / f"turn-{t:02d}" / "2-actors" / "eu.md")
                  for t in turns}
        # Turn 1 belongs to no block, but it carries the reader's opening
        # choice — the single most important proposal in the run — so a
        # stage-1 block checks it on behalf of the branch it starts.
        checks = ([1] if block["stage"] == 1 else []) + list(block["turns"])
        for t in checks:
            if t not in parsed:
                continue
            node = (f"turn-01 (opening \u2192 {block['block']})" if t == 1
                    else f"turn-{t:02d}-{block['block']}")
            later = [x for x in turns if x > t]

            proposal = parsed[t]["new_measure"]
            if words(proposal) and later and not any(
                    any(words(proposal) & words(m["name"]) for m in parsed[x]["portfolio"])
                    for x in later):
                blob = ""
                for name in ("4-world-state.md", "5-notepad.md"):
                    f = rd / f"turn-{t:02d}" / name
                    if f.is_file():
                        blob += f.read_text(encoding="utf-8")
                if not DEFERRED.search(blob):
                    rows.append({"node": node, "turn": t, "block": block["block"],
                                 "kind": "never entered", "measure": proposal})

            if t == 1:
                continue  # the vanish check below belongs to block turns only
            if t + 1 in parsed:
                nxt = parsed[t + 1]
                gone = [c["name"] for c in nxt["cancelled"]] + \
                       [c["name"] for c in parsed[t]["cancelled"]]
                for m in parsed[t]["portfolio"]:
                    if any(same(m["name"], n["name"]) for n in nxt["portfolio"]):
                        continue
                    if m.get("finished") or (m.get("finish") is not None and m["finish"] <= t) \
                            or any(same(m["name"], c) for c in gone):
                        continue
                    rows.append({"node": node, "turn": t, "block": block["block"],
                                 "kind": "vanished", "measure": m["name"]})

    rows.sort(key=lambda r: (r["turn"], r["block"]))
    out = [
        "# Ledger gaps in the story path runs",
        "",
        "Generated by `ledger_gaps.py`. Measures the portfolio lost, mapped onto the story",
        "node a writer works in. Cause and measured rates: "
        "[`../../../docs/proposals/persistent-state-custody.md`](../../../docs/proposals/persistent-state-custody.md).",
        "",
        "Deferrals that state a reason are *not* listed, even when they are never resolved —",
        "the A2 opening choice is the example, and it is written up separately in `README.md`.",
        "",
        "**How to use this.** Before writing a turn listed here, check the world state rather",
        "than the portfolio. A *never entered* measure may be narrated as proposed in its own",
        "turn, but nothing later should treat it as running. A *vanished* measure was real and",
        "then stopped being carried; the world state usually keeps describing it.",
        "",
        f"{len(rows)} occurrences across {len({r['block'] for r in rows})} of the 42 blocks. "
        f"A ✍ marks a node whose prose is already written.",
        "",
        "| node | period | written | kind | measure |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        mark = "✍" if r["node"] in written else ""
        out.append(f"| `{r['node']}` | {periods[str(r['turn'])]} | {mark} | "
                   f"{r['kind']} | {r['measure']} |")
    out.append("")
    (STORY / "ledger-gaps.md").write_text("\n".join(out), encoding="utf-8")
    already = sum(1 for r in rows if r["node"] in written)
    print(f"ledger-gaps.md: {len(rows)} occurrences, {already} in nodes already written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
